### PR TITLE
IDEA-friendly PluginsAndFeatures/azure-toolkit-for-intellij project

### PR DESCRIPTION
**Pull request by shalupov**
* fixed version of Gradle used for both building and syncing project in IDE
* no need to import project in IDE,A just open the project folder
* no VCS popup in IDEA about enabling Git integration
* no Gradle import dialog in IDEA

### CODE REVIEW

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Comment by Eskibear** [comment]
run tests.

**Comment by Eskibear** [comment]
ok to test

**Comment by Eskibear** [comment]
Build failed: script for dependency comparison was not updated in Jenkins server.

**Comment by Eskibear** [comment]
retest this please

**Pull request merged**
