### PR TITLE
Add sparkserverless Rest API support with updated swagger spec

### PR DESCRIPTION
**Pull request by t-rufang**
You can check the updated swagger spec file [in this commit](https://github.com/hnihanth/azure-rest-api-specs-pr/commit/b8af922e1f28755ebc6d4e4712a3ea2ff811fd99#diff-658da7deac6b963de91cc4f57db9680d)

### CODE REVIEW

**Comment by wezhang** [comment]
LGTM! Thanks! I’ll merge it with my changes.

**Comment by wezhang** [comment]
merged in #1650

**Comment by t-rufang** [comment]
Swagger spec updated. You can check the updated swagger spec [in this commit](https://github.com/hnihanth/azure-rest-api-specs-pr/commit/bfbb9957b4cd02200a37f725eef0328749f56320#diff-658da7deac6b963de91cc4f57db9680d)

**Comment by t-rufang** [comment]
Swagger spec updated. You can check the updated swagger spec [in this commit](https://github.com/hnihanth/azure-rest-api-specs-pr/commit/a7adbf19902c216234f5fb64e94beefbea584a2a#diff-658da7deac6b963de91cc4f57db9680d)

**Pull request closed without merging**
