### PR TITLE
Split azure intellij plugin storage lib

### PR DESCRIPTION
**Pull request by rafaelldi**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Hello! In this PR I've created a separate `azure-intellij-plugin-storage-java` library and moved the java-related code from the `azure-intellij-plugin-storage` there.

What was done:
1. A new `azure-intellij-plugin-storage-java` library was created;
2. The `com.microsoft.azure.toolkit.intellij.storage.code` classes were moved there because they depend on the `azure-intellij-resource-connector-lib-java` library;
3. Split `StorageAccountResourceDefinition` into `StorageAccountResourceDefinition` and `BaseStorageAccountResourceDefinition`, since this class implements the `SpringSupported` interface;
4. `StorageAccountResourcePanel` is moved to the new library, since it depends on `StorageAccountResourceDefinition`;
5. Also, I created new `IntellijJavaStorageActionsContributor` and moved one `CONNECT` handler there, as it also depends on `StorageAccountResourceDefinition`.

Does this close any currently open issues?
------------------------------------------
No

Any relevant logs, screenshots, error output, etc.?
-------------------------------------
None

Any other comments?
-------------------

Has this been tested?
---------------------------
- [ ] Tested

### CODE REVIEW

**Comment by rafaelldi** [comment]
Hi, folks. Sorry for pinging, but could you please take a look?

**Comment by wangmingliang-ms** [comment]
> Hi, folks. Sorry for pinging, but could you please take a look?

Sorry for the late reply, busy with some other tasks🤣. soon.

**Comment by wangmingliang-ms** [comment]
Hi, @rafaelldi , we just migrated to new gradle intellij plugin (v2.0) and Kotlin DSL. can you fix these PRs to use Kotlin?

**Review by wangmingliang-ms — APPROVED** [review]
LGTM

**Comment by wangmingliang-ms** [comment]
Due to security constraints, the pipeline doesn't work for PRs from forked repo, I will build and test it locally for temp and then merge it if all works. thanks.

**Comment by rafaelldi** [comment]
Thank you very much!

**Comment by wangmingliang-ms** [comment]
tested, all work

**Pull request merged**
