### PR TITLE
[WIP] Support IntelliJ IDEA 183

### PR DESCRIPTION
**Pull request by Eskibear**
Work item: #2057 

To resolve:
- [ ] Kotlin compilation error. (supposed to be fixed in #2247 )
- [ ] ~Script for Production not updated~. (Will update later if no regression issues are found.)

### CODE REVIEW

**Comment by Eskibear** [comment]
With 183 SDK:
```
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/actions/SparkAppSubmitContext.kt: (28, 1): Class 'SparkAppSubmitContext' is not abstract and does not implement abstract member @Nullable public abstract fun getData(@NotNull @NonNls p0: String): Any? defined in com.intellij.openapi.actionSystem.DataContext
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/actions/SparkAppSubmitContext.kt: (31, 5): 'getData' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/actions/SparkSubmitJobAction.kt: (50, 5): 'update' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/actions/SparkSubmitJobAction.kt: (51, 22): Type mismatch: inferred type is AnActionEvent? but AnActionEvent was expected
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/RunSparkConsoleActionDelegate.kt: (43, 5): 'update' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/RunSparkScalaConsoleAction.kt: (135, 25): One type argument expected. Use 'RunConfigurationBase<*>' if you don't want to pass type arguments
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/RunSparkScalaLivyConsoleAction.kt: (35, 25): One type argument expected. Use 'RunConfigurationBase<*>' if you don't want to pass type arguments
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkConsoleExecuteAction.kt: (38, 5): 'update' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (45, 31): 2 type arguments expected for class ModuleBasedConfiguration<ConfigurationModule : RunConfigurationModule!, T : Any!>
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (54, 5): 'getConfigurationEditor' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (55, 13): Type mismatch: inferred type is SparkScalaLivyConsoleRunConfigurationEditor but SettingsEditor<out RunConfiguration> was expected
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (57, 5): 'getValidModules' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (58, 42): Unresolved reference: project
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (58, 68): Unresolved reference: project
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (62, 5): 'getState' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (64, 17): Unresolved reference: name
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (69, 78): Unresolved reference: project
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (72, 5): 'checkSettingsBeforeRun' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfiguration.kt: (73, 15): Unresolved reference: checkSettingsBeforeRun
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfigurationFactory.kt: (33, 16): Type mismatch: inferred type is SparkScalaLivyConsoleRunConfiguration but RunConfiguration was expected
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfigurationFactory.kt: (36, 5): 'createConfiguration' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkScalaLivyConsoleRunConfigurationFactory.kt: (38, 16): Type mismatch: inferred type is SparkScalaLivyConsoleRunConfiguration but RunConfiguration was expected
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/console/SparkSendSelectionToConsoleAction.kt: (36, 5): 'update' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/action/SparkRunConfigurationAction.kt: (50, 5): 'update' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/action/SparkRunConfigurationAction.kt: (51, 22): Type mismatch: inferred type is AnActionEvent? but AnActionEvent was expected
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/action/SparkRunConfigurationAction.kt: (95, 25): One type argument expected. Use 'RunConfigurationBase<*>' if you don't want to pass type arguments
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (40, 33): 2 type arguments expected for class ModuleBasedConfiguration<ConfigurationModule : RunConfigurationModule!, T : Any!>
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (41, 5): 'getConfigurationEditor' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (42, 16): Type mismatch: inferred type is SparkFailureTaskDebugSettingsEditor but SettingsEditor<out RunConfiguration> was expected
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (45, 5): 'getState' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (47, 52): Unresolved reference: name
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (49, 54): Unresolved reference: name
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (55, 5): 'readExternal' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (56, 15): Unresolved reference: readExternal
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (60, 5): 'writeExternal' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (61, 15): Unresolved reference: writeExternal
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfiguration.kt: (66, 5): 'getValidModules' overrides nothing
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfigurationFactory.kt: (32, 32): Type argument is not within its bounds: should be subtype of 'RunConfiguration!'
azure-toolkit-for-intellij/src/com/microsoft/azure/hdinsight/spark/run/configuration/SparkFailureTaskDebugConfigurationFactory.kt: (38, 16): Type mismatch: inferred type is SparkFailureTaskDebugConfiguration but RunConfiguration was expected
```

**Comment by Eskibear** [comment]
@wezhang I've also improved the script to make it clearer. From the Jenkins CI we know that the build command is actually:
```
./gradlew clean buildPlugin -s -Pintellij_version=IC-183.3795.13 -Pdep_plugins=org.intellij.scala:2018.3.2
```

**Comment by wezhang** [comment]
Thanks @Eskibear ! I can repro this.

**Comment by wezhang** [comment]
Merged into #2247

**Pull request closed without merging**
