### PR TITLE
Separate Java-related logic from common libraries

### PR DESCRIPTION
**Pull request by sdubov**
What does this implement/fix? Explain your changes.
---------------------------------------------------
- Split resource connector manager library
- Split database library
- Remove unused dependency from java-related modules for port of libraries

Does this close any currently open issues?
------------------------------------------
Base refactoring to support non-java related plugins

Any relevant logs, screenshots, error output, etc.?
-------------------------------------
None

Any other comments?
-------------------
None

Has this been tested?
---------------------------
- [ ] Tested

### CODE REVIEW

**Comment by sdubov** [comment]
@microsoft-github-policy-service agree [company="JetBrains"]

**Comment by sdubov** [comment]
@microsoft-github-policy-service agree

**Comment by wangmingliang-ms** [comment]
let it build first,

**Comment by wangmingliang-ms** [comment]
thanks, it looks good to me, 
I will merge this PR forcedly because the pipelines have something wrong.

**Pull request merged**
