### PR TITLE
Separate Java-related code from appservice library

### PR DESCRIPTION
**Pull request by rafaelldi**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Split appservice library

Does this close any currently open issues?
------------------------------------------
Base refactoring to support non-java related plugins

Any relevant logs, screenshots, error output, etc.?
-------------------------------------
None

Any other comments?
-------------------
None

Has this been tested?
---------------------------
- [ ] Tested

### CODE REVIEW

**Comment by rafaelldi** [comment]
@microsoft-github-policy-service agree

**Comment by rafaelldi** [comment]
Hi @wangmingliang-ms. Could you please tell me if there are any problems with this request? Is there anything I should fix?

**Comment by wangmingliang-ms** [comment]
> Hi @wangmingliang-ms. Could you please tell me if there are any problems with this request? Is there anything I should fix?

No, nothing to fix for the moment.
the pipelines have something wrong with the settings, causing it not running. I will review the PR and build the PR locally, thanks.

**Comment by wangmingliang-ms** [comment]
@rafaelldi, I am not sure what is wrong, the code seems OK, but did you see the below error when debugging the plugin with your branch (after merging `develop` into your branch)?
image

**Comment by rafaelldi** [comment]
Actually, I didn't face with this problem. I decided to remove the separate `AzureJavaRunConfigurationBase` base class and move `AzureRunConfigurationBase` to the java-specific library. Maybe it will fix the problem.

**Comment by wangmingliang-ms** [comment]
@rafaelldi the error disappears. 
We migrated to Gradle 7.x and Java 17 recently, causing some conflicts, I resolved them and merged the branch into `develop` locally. thanks.

**Comment by rafaelldi** [comment]
Great! Thank you

**Pull request merged**
