### PR TITLE
Mistake in languages

### PR DESCRIPTION
**Pull request by dautovri**

### CODE REVIEW

**Comment by martinsawicki** [comment]
@visionalsky something for you to evaluate. thanks

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Comment by voidfunction** [comment]
Can one of the admins verify this patch?

**Comment by voidfunction** [comment]
@dautovri Thanks for your contribution. The typos have been fixed.

**Pull request closed without merging**
