### PR TITLE
Separate Java-related code from guidance library

### PR DESCRIPTION
**Pull request by rafaelldi**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Hello! I created an `azure-intellij-plugin-guidance-java` library and moved all the java-specific code from the `azure-intellij-plugin-guidance` base library there. This will allow us to use this library (and the `azure-intellij-plugin-appservice` library) for other languages.

Does this close any currently open issues?
------------------------------------------
No

Any relevant logs, screenshots, error output, etc.?
-------------------------------------
None

Any other comments?
-------------------
…

Has this been tested?
---------------------------
- [ ] Tested

### CODE REVIEW

**Comment by rafaelldi** [comment]
I fixed the merge conflicts

**Comment by rafaelldi** [comment]
Hello @Flanker32! I apologize for pinging you, but could you please take a look. I'm afraid of new merge conflicts.

**Review by Flanker32 — APPROVED** [review]
LGTM

**Comment by Flanker32** [comment]
@rafaelldi Thanks a lot for the efforts and sorry for the late response, the PR looks fine to me~

**Comment by rafaelldi** [comment]
Thank you!

**Pull request merged**
