### PR TITLE
Add Redis explorer integration test

### PR DESCRIPTION
**Pull request by songkaiape**
Add Redis explorer integration test case. This case only run in nonmock mode.

### CODE REVIEW

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Comment by adashen** [comment]
retest this please.

**Comment by jdneo** [comment]
retest this please.

**Comment by jdneo** [comment]
retest this please.

**Comment by jdneo** [comment]
ok to test

**Comment by Eskibear** [comment]
ok to test

**Pull request merged**
