### PR TITLE
Cs dev redis

### PR DESCRIPTION
**Pull request by jdneo**
This PR is related to the redis cache node:
1. merge the code from private repo to public repo
2. reimplement UI logic of the intellij part

### CODE REVIEW

**Comment by voidfunction** [comment]
Can one of the admins verify this patch?

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Comment by jdneo** [comment]
@adashen @testforstephen @Eskibear

**Comment by testforstephen** [comment]
add to whitelist

**Pull request merged**
