### PR TITLE
Fix the jobconfig empty issue

### PR DESCRIPTION
**Pull request by wezhang**
Fill the Submission parameter jobconfig required keys with the empty value

Signed-off-by: Zhang Wei <zhwe@microsoft.com>

### CODE REVIEW

**Comment by wezhang** [comment]
to fix #786

**Comment by wezhang** [comment]
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'mars' from location http://download.eclipse.org/releases/mars: Unable to read repository at http://download.eclipse.org/releases/mars/content.xml. Connect to download.eclipse.org:80 timed out -> [Help 1]

**Comment by Eskibear** [comment]
Since `download.eclipse.org` is down, it's no use to re-trigger the build for the moment.

**Comment by Eskibear** [comment]
retest this please

**Pull request merged**
