### PR TITLE
workaround to speed up installation after auto generating manifest.mf

### PR DESCRIPTION
**Pull request by Eskibear**
This is a backup for [PR#468](https://github.com/Microsoft/azure-tools-for-java/pull/468).
In [PR#468](https://github.com/Microsoft/azure-tools-for-java/pull/468), it's observed stuck at `committing the provisioning operation` stage for a few minutes during installation of eclipse plugin.

Investigation reveals that it's due to specific version number of packages in `Export-Package`. (removing the version number fixes the issue, but `maven-bundle-plugin` generate the version number by default)

In this PR, I simply overwrite `version` and `uses:` attributes with nonsense values to speed it up. BUT I think these tricky `version:0.0.0` might potentially cause troubles in the future.

Please share a better solution if you have any idea about this issue, thanks.

### CODE REVIEW

**Comment by voidfunction** [comment]
Can one of the admins verify this patch?

**Comment by Eskibear** [comment]
retest this please

**Comment by adashen** [comment]
retest this please

**Comment by Eskibear** [comment]
@adashen travis retest is manually triggered in details page if you are admin.

For Jenkins, this PR should modify the jobs.

**Comment by testforstephen** [comment]
retest this please

**Comment by testforstephen** [comment]
retest this please

**Pull request merged**
