### PR TITLE
Place null in catch, because it will return null when an exception ha…

### PR DESCRIPTION
**Pull request by pi1024e**
…ppens anyway.

### CODE REVIEW

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Comment by pi1024e** [comment]
You posted this the second I clicked "Send Pull Request". Are you a bot or person?

**Comment by Flanker32** [comment]
@t-rufang Please have a look.

**Comment by t-rufang** [comment]
@pi1024e This PR doesn't change any behaviour of the method `convertToObjectQuietly`. If an IOException happens in this method, this method will swallow the exception and return `null` no matter with or without this patch. I wonder you want to add this patch? Have you ever run into any exception that you want to catch?

**Comment by t-rufang** [comment]
Hi @pi1024e , I will close this issue since there are no updates. Feel free to reopen it if you have other concerns.

**Pull request closed without merging**
