### PR TITLE
Add Intellij gitignores and remove IDEA local files

### PR DESCRIPTION
**Pull request by wezhang**
Signed-off-by: Zhang Wei <zhwe@microsoft.com>

### CODE REVIEW

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Comment by wezhang** [comment]
why `.gradle/buildOutputCleanup/cache.properties` file is strong dependent?

```
* What went wrong:
java.io.FileNotFoundException: /home/travis/build/Microsoft/azure-tools-for-java/.gradle/buildOutputCleanup/cache.properties (No such file or directory)
> /home/travis/build/Microsoft/azure-tools-for-java/.gradle/buildOutputCleanup/cache.properties (No such file or directory)
```

**Comment by wezhang** [comment]
Issue #424 created

**Comment by Eskibear** [comment]
as far as I know, simply removing the whold `.gradle` folder will fix the problem, it will automatically re-create `.gradle` folder when executing `./gradlew assemble`.

**Comment by wezhang** [comment]
@Eskibear Thanks! I'll try to remove all of them.

**Comment by wezhang** [comment]
@Eskibear It works!, `./gradlew assemble` passed!

**Comment by wezhang** [comment]
Hit #421

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Pull request merged**
