### PR TITLE
install jarfile to local repository for clearer dependencies

### PR DESCRIPTION
**Pull request by Eskibear**
* Fix historical typos.
* Remove system scope dependency of `applicationinsights-management-1.0.3.jar`

### CODE REVIEW

**Comment by voidfunction** [comment]
Can one of the admins verify this patch?

**Comment by voidfunction** [comment]
@Eskibear @adashen I suppose the gradle build file should be change:
https://github.com/Microsoft/azure-tools-for-java/blob/develop/PluginsAndFeatures/azure-toolkit-for-intellij/build.gradle#L71

**Comment by Eskibear** [comment]
@voidfunction I don't think so. As a dependency, `applicationinsights-management-1.0.3.jar` is still copied to folder `AddLibrary/AzureLibraries/com.microsoft.azuretools.sdk/dependencies`.

**Comment by Eskibear** [comment]
@voidfunction In fact it doesn't break the building procedure of eclipse plugin at all. And one of the benefits is that now you can safely clear all jar files in `AddLibrary/AzureLibraries/com.microsoft.azuretools.sdk/dependencies` folder before re-build, so as to avoid  [such kind of mistakes](https://github.com/Microsoft/azure-tools-for-java/commit/5d7cb5bc5fff176c2ceb81fea27f906de487ee5b)

**Pull request merged**
