### PR TITLE
refine Scala downlaoding tips for non-HDInsgiht customers

### PR DESCRIPTION
**Pull request by voidfunction**

### CODE REVIEW

**Comment by voidfunction** [comment]
build error: 
```
Scenario: factory helper unit test  Time elapsed: 0.002 sec  <<< ERROR!
com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.net.BindException: Address already in use
	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:145)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchRemoteDebugJobScenario.mockLivyService(SparkBatchRemoteDebugJobScenario.java:155)
	at ✽.Given setup a mock livy service for POST request 'http://127.0.0.1:9876/batches' to return '{"id":9, "state":"starting","appId":"application_1492415936046_0015","appInfo":{"driverLogUrl":"https://spkdbg.azurehdinsight.net/yarnui/10.0.0.15/node/containerlogs/container_e02_1492415936046_0015_01_000001/livy","sparkUiUrl":"https://spkdbg.azurehdinsight.net/yarnui/hn/proxy/application_1492415936046_0015/"},"log":["\t ApplicationMaster RPC port: -1","\t queue: default","\t start time: 1492569369011","\t final status: UNDEFINED","\t tracking URL: https://spkdbg.azurehdinsight.net/yarnui/hn/proxy/application_1492415936046_0015/","\t user: livy","17/04/19 02:36:09 INFO ShutdownHookManager: Shutdown hook called","17/04/19 02:36:09 INFO ShutdownHookManager: Deleting directory /tmp/spark-1984dc9d-acd4-4648-9104-398431590f8e","YARN Diagnostics:","AM container is launched, waiting for AM container to Register with RM"]}' with status code 200(com/microsoft/azure/hdinsight/spark/common/SparkBatchRemoteDebugJobScenario.feature:12)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:132)
	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:143)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchRemoteDebugJobScenario.mockLivyService(SparkBatchRemoteDebugJobScenario.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:300)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
```

link: http://vscjavaci.cloudapp.net/job/AzureToolsManager_PR/665/console

**Comment by voidfunction** [comment]
retest it please.

**Comment by voidfunction** [comment]
retest this please

**Comment by voidfunction** [comment]
@wezhang Seems we have a build conflict about opened port.

**Comment by wezhang** [comment]
reopen #819

**Pull request merged**
