### PR TITLE
Auto refresh spark clusters drowdown list

### PR DESCRIPTION
**Pull request by ziyel**

### CODE REVIEW

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Comment by voidfunction** [comment]
Can one of the admins verify this patch?

**Comment by ziyel** [comment]
retest please

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Comment by voidfunction** [comment]
Can one of the admins verify this patch?

**Comment by voidfunction** [comment]
ok to test

**Pull request merged**
