### PR TITLE
Add place holder to remind users when no slot to deploy

### PR DESCRIPTION
**Pull request by SummerSun**
Remind the users that when there is no slot to deploy and we are going to deploy the web app instead.

comment

### CODE REVIEW

**Comment by jdneo** [comment]
Why we do not have a default 'slot' which represents the Web App itself

**Comment by SummerSun** [comment]
Use a placeholder `<No deployment slot is found, will deploy the web app.>` to remind users that there is no deployment slot and we are going to deploy the web app instead.

**Comment by Eskibear** [comment]
Recap:

> Why we do not have a default 'slot' which represents the Web App itself

From the GIF, I see `staging` and `test` slots in a web app. So how do I deploy to the web app itself?

**Comment by Eskibear** [comment]
> Recap:
> 
> > Why we do not have a default 'slot' which represents the Web App itself
> 
> From the GIF, I see `staging` and `test` slots in a web app. So how do I deploy to the web app itself?

Oh I see, am I supposed to uncheck the checkbox "Deploy to slot"?

**Comment by SummerSun** [comment]
@Eskibear  Yep

**Comment by SummerSun** [comment]
This PR discussed two options for reminding users that we are going to deploy the web app when there are no deployment slots:
- Show the information message at the bottom of the dialog
- Use the placeholder in the deployment slot combo box

But the above two options are kind of workarounds. Providing the option to create a deployment slot to deploy when there is none makes the scenario a completed one. So we close this PR and finish the scenario in another one to support the option for creating if not existing.

**Pull request closed without merging**
