### PR TITLE
chmod +x for Unix scripts

### PR DESCRIPTION
**Pull request by shalupov**

### CODE REVIEW

**Comment by vscjavaci** [comment]
Can one of the admins verify this patch?

**Comment by Eskibear** [comment]
ok to test

**Comment by Eskibear** [comment]
run tests.

**Comment by Eskibear** [comment]
It looks something wrong with the Jenkins pull request builder plugin. Investigating.

**Comment by Eskibear** [comment]
jenkins server issue fixed.  run tests.

**Pull request merged**
