### PR TITLE
Disable Spark configuration RUN action

### PR DESCRIPTION
**Pull request by wezhang**
Enable it later after defining the action clearly.

Signed-off-by: Zhang Wei <zhwe@microsoft.com>

### CODE REVIEW

**Comment by wezhang** [comment]
To fix #730

**Comment by wezhang** [comment]
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'mars' from location http://download.eclipse.org/releases/mars: Unable to read repository at http://download.eclipse.org/releases/mars/compositeContent.jar. Read timed out -> [Help 1]

**Comment by Eskibear** [comment]
Since the `download.eclipse.org` keeps down, I think this PR can be merged without CI, if you can confirm there would be no regression or other issues. What do you think?
@djlan @wezhang

**Comment by wezhang** [comment]
@Eskibear I've tested it in local, I suppose it can be merged bypass CI.

**Pull request merged**
